services:

  app:
    image: rssbridge/rss-bridge:2025-08-05
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      frontend:
    volumes:
      - config:/config

networks:
  frontend:
    name: proxy_frontend
    external: true

volumes:
  config:
